# This file was generated by GoReleaser. DO NOT EDIT.
cask "today" do
  name "today"
  desc "A terminal dashboard that puts everything you need to start your day in one place"
  homepage "https://github.com/jonmilley/today-tui"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "today"

  on_macos do
    on_intel do
      url "https://github.com/jonmilley/today-tui/releases/download/v#{version}/today-tui_darwin_amd64.tar.gz"
      sha256 "774d6fb6326bdb4b6b45f21abb9947f7bc149294f84b1bfe2c5df8d696eaa780"
    end
    on_arm do
      url "https://github.com/jonmilley/today-tui/releases/download/v#{version}/today-tui_darwin_arm64.tar.gz"
      sha256 "7128a88c215f9dcee9f3cfefef3b9a09ee9a785c8883d5030a06488aefdfd8b1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jonmilley/today-tui/releases/download/v#{version}/today-tui_linux_amd64.tar.gz"
      sha256 "3d16b9b1b11fa93e15b4fdab8f67ee871a1e419b90ff4fce2deeb3fa6e9db801"
    end
    on_arm do
      url "https://github.com/jonmilley/today-tui/releases/download/v#{version}/today-tui_linux_arm64.tar.gz"
      sha256 "f5851834a2bb3fbd6a7862a603297beb022f1180b8c6287f2098d1f16e0a085d"
    end
  end

  # No zap stanza required
end
