# This file was generated by GoReleaser. DO NOT EDIT.
cask "today" do
  version "0.2.0"

  on_macos do
    on_intel do
      url "https://github.com/jonmilley/today-tui/releases/download/v#{version}/today-tui_darwin_amd64.tar.gz"
      sha256 "ac9b83ec60e5b05d5ddf6c62efda221142306f2f9b201c6d7cb167fba741ea73"
    end
    on_arm do
      url "https://github.com/jonmilley/today-tui/releases/download/v#{version}/today-tui_darwin_arm64.tar.gz"
      sha256 "659dd48a023897ff29d32feefc02c7df8bdd96449b4ce23ff1fab962dd2b5d0e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jonmilley/today-tui/releases/download/v#{version}/today-tui_linux_amd64.tar.gz"
      sha256 "0ebe1f28b15083896bd0e86b2152cb8c26cf0fb39571b8b4823f422fba083519"
    end
    on_arm do
      url "https://github.com/jonmilley/today-tui/releases/download/v#{version}/today-tui_linux_arm64.tar.gz"
      sha256 "c69623245bc602f82dbd344fb870487b69bf6d97a4edc851dd3057ef4c71e55b"
    end
  end

  name "today"
  desc "A terminal dashboard that puts everything you need to start your day in one place"
  homepage "https://github.com/jonmilley/today-tui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "today"

  # No zap stanza required

end
